version: '3'

volumes:
  votingserver-volume:

networks:
  votingserver-network:

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      name: voting
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret_mongo_password
    ports:
      - 27017:27017
    networks:
      - votingserver-network